name: flutter_paystack_client
description: Flutter Paystack payment plugin with support for Web, Android and iOS
version: 0.1.1
homepage: https://github.com/djade007/flutter_paystack_client
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  flutter_paystack:
    git:
      url: https://github.com/lazicah/flutter_paystack.git

dev_dependencies:
  flutter_test:
    sdk: flutter
